[project]
name = "chktrade"
version = "0.1.0"
description = "All in one trade platform"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "textual>=2.1.0",
    "textual-dev>=1.7.0",
]
