new_trade:
  custom_inputs:
    - title: setup
      type: option
      options:
        - title: News
          timeout: 3
          popup: Nope
        - title: FOMO
          timeout: 34
        - title: Test
          popup: Nope
    - title: Is BTC Strong?
      type: bool
      popup: Nope
      timeout: 23
    - title: Is SPX Strong?
      type: bool
      timeout: 23
      popup: Nope
    - title: Is There Bad News
      type: bool
      timeout: 23
      popup: Nope
  checklist:
    - Abc
    - Test
    
    