new_trade:
  custom_inputs:
    setup:
      title: setup
      type: option
      options:
        - title: News
          timeout: 3
          popup: Nope
        - title: FOMO
          timeout: 34
        - title: Test
          popup: Nope
    btcStrong:
      title: Is BTC Strong?
      type: bool
      popup: Nope
      timeout: 23
    spx:
      title: Is SPX Strong?
      type: bool
      timeout: 23
      popup: Nope
    badNews:
      title: Is There Bad News
      type: bool
      timeout: 23
      popup: Nope
    badNews2:
      title: Is There Bad News
      type: bool
      timeout: 23
      popup: Nope
    badNews3:
      title: Is There Bad News
      type: bool
      timeout: 23
      popup: Nope
  checklist:
    - Abc
    - Test
    
    